Repository GoogleChromeLabs/bubblewrap, pull requests merged in 2020-11, with the labels that each got.

#384 Added progress bar when downloading SDKs
  packages/cli/src/lib/AndroidSdkToolsInstaller.ts
  packages/cli/src/lib/JdkInstaller.ts
  packages/cli/src/lib/Prompt.ts
  packages/cli/src/lib/config.ts
  packages/cli/src/lib/strings.ts
  packages/cli/src/spec/mock/MockPrompt.ts
  packages/core/src/index.ts
Labels: enhancement

#390 Adds the OrientationLock to WebManifest
  packages/core/src/lib/types/WebManifest.ts
Labels: enhancement

#385 Update abh-alpha to 2.1.0-alpha01
  packages/core/src/lib/TwaManifest.ts
  packages/core/src/lib/features/FeatureManager.ts
  packages/core/src/spec/lib/features/FeatureManagerSpec.ts
Labels: enhancement

#388 Web share target support
  packages/core/src/lib/TwaGenerator.ts
  packages/core/src/lib/types/WebManifest.ts
  packages/core/src/lib/util.ts
  packages/core/template_project/app/build.gradle
  packages/core/template_project/app/src/main/AndroidManifest.xml
Labels: enhancement

#391 shareTarget derives full action URL
  packages/core/src/lib/TwaManifest.ts
  packages/core/template_project/app/src/main/AndroidManifest.xml
Labels: enhancement

#392 Handles orientation in twa-manifest.json, AndroidManifest.xml and init
  packages/cli/README.md
  packages/cli/src/lib/Cli.ts
  packages/cli/src/lib/cmds/help.ts
  packages/cli/src/lib/cmds/init.ts
  packages/cli/src/lib/inputHelpers.ts
  packages/cli/src/lib/strings.ts
  packages/core/src/index.ts
  packages/core/src/lib/TwaManifest.ts
  packages/core/src/spec/lib/TwaManifestSpec.ts
  packages/core/template_project/app/build.gradle
  packages/core/template_project/app/src/main/AndroidManifest.xml
Labels: enhancement

#394 Adds publish commands to package.json
  package.json
Labels: internal

#395 Escapes commas in dname when generating the signing key
  packages/core/src/lib/jdk/KeyTool.ts
  packages/core/src/spec/lib/jdk/KeyToolSpec.ts
Labels: bug

#398 Handles new directory structure for Android SDK
  packages/core/src/lib/androidSdk/AndroidSdkTools.ts
Labels: bug

#399 Adds screen orientation to LauncherActivity
  packages/core/src/lib/TwaGenerator.ts
  packages/core/src/lib/util.ts
  packages/core/template_project/app/build.gradle
  packages/core/template_project/app/src/main/AndroidManifest.xml
Labels: bug

#408 Sets LaunchActivity orientation value in the XML
  packages/core/template_project/app/build.gradle
  packages/core/template_project/app/src/main/AndroidManifest.xml
Labels: bug

#412 Rename classConstructor to onCreate.
  packages/core/src/lib/features/EmptyFeature.ts
  packages/core/src/lib/features/Feature.ts
  packages/core/src/lib/features/FeatureManager.ts
  packages/core/src/lib/features/LocationDelegationFeature.ts
  packages/core/src/lib/features/PlayBillingFeature.ts
  packages/core/src/spec/lib/features/FeatureManagerSpec.ts
  packages/core/template_project/app/src/main/java/DelegationService.java
Labels: internal
