Repository GoogleChromeLabs/bubblewrap, pull requests merged in 2020-05, with the labels that each got.

#148 Fixes --sdk_root parameter on Windows
  package-lock.json
  packages/core/src/lib/androidSdk/AndroidSdkTools.ts
  packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts
Labels: bug

#157 Improves AndroidSdkTools errors
  packages/cli/src/lib/cmds/build.ts
  packages/core/src/lib/androidSdk/AndroidSdkTools.ts
  packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts
Labels: enhancement

#158 Updated Documentation for more detailed steps on requirements
  packages/cli/README.md
Labels: documentation

#160 CLI checks minimum supported Node.js version
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/lib/Cli.ts
Labels: enhancement

#165 Runs npm update and npm audit fix
  package-lock.json
  package.json
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/validator/package-lock.json
  packages/validator/package.json
Labels: internal

#164 Update main README.md to help devs get started
  README.md
Labels: documentation

#178 Prevent build failing when PSI fails
  packages/cli/src/lib/cmds/build.ts
  packages/cli/src/lib/cmds/install.ts
  packages/core/src/lib/Log.ts
  packages/core/src/lib/androidSdk/AndroidSdkTools.ts
  packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts
  packages/validator/src/lib/PwaValidator.ts
Labels: bug
