Repository GoogleChromeLabs/bubblewrap, pull requests merged in 2020-07, with the labels that each got.

#217 Fixes Unhandled Promise Rejections
  packages/cli/src/lib/Cli.ts
  packages/cli/src/lib/config.ts
  packages/cli/src/spec/configSpec.ts
Labels: bug

#215 Put password in quotes to allow more characters in password
  packages/core/src/lib/androidSdk/AndroidSdkTools.ts
  packages/core/src/lib/jdk/JdkHelper.ts
  packages/core/src/lib/util.ts
  packages/core/src/spec/lib/androidSdk/AndroidSdkToolsSpec.ts
Labels: bug

#230 Refactors user prompts
  packages/cli/src/lib/Prompt.ts
  packages/cli/src/lib/cmds/build.ts
  packages/cli/src/lib/cmds/init.ts
  packages/cli/src/lib/cmds/update.ts
  packages/cli/src/lib/inputHelpers.ts
  packages/cli/src/lib/strings.ts
  packages/cli/src/spec/inputHelpersSpec.ts
  packages/core/src/index.ts
  packages/core/src/lib/TwaManifest.ts
Labels: internal

#232 Improve prompts for the `init` command
  packages/cli/src/lib/Prompt.ts
  packages/cli/src/lib/cmds/init.ts
  packages/cli/src/lib/strings.ts
Labels: enhancement

#238 Uses a progress bar when generating Projects
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/lib/cmds/init.ts
  packages/cli/src/lib/cmds/shared.ts
  packages/cli/src/lib/cmds/update.ts
  packages/cli/src/lib/strings.ts
  packages/core/src/lib/TwaGenerator.ts
Labels: enhancement

#241 GradleWrapper can call bundleRelease
  packages/core/src/lib/GradleWrapper.ts
  packages/core/src/lib/util.ts
  packages/core/src/spec/lib/GradleWrapperSpec.ts
Labels: enhancement

#246 Updates dependencies
  package-lock.json
  package.json
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/validator/package-lock.json
  packages/validator/package.json
Labels: dependencies

#247 Update CLI README.md with correct JDK path content on MacOS
  packages/cli/README.md
Labels: documentation

#248 Adds a wrapper for jarsigner
  packages/core/src/index.ts
  packages/core/src/lib/jdk/JarSigner.ts
  packages/core/src/spec/lib/jdk/JarSignerSpec.ts
Labels: enhancement

#255 Use the correct default key alias on `init`
  packages/cli/src/lib/cmds/init.ts
Labels: bug

#256 Fix maskable icon glitch
  packages/core/template_project/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
Labels: bug

#261 Support of Android 11 and CrOS support update
  packages/core/template_project/app/build.gradle
  packages/core/template_project/build.gradle
  packages/core/template_project/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#265 Clarifies passwords prompt on `build` command
  packages/cli/src/lib/cmds/build.ts
  packages/cli/src/lib/strings.ts
Labels: enhancement
