Repository GoogleChromeLabs/bubblewrap, pull requests merged in 2020-09, with the labels that each got.

#317 ValidatePathError
  packages/core/src/index.ts
  packages/core/src/lib/androidSdk/AndroidSdkTools.ts
  packages/core/src/lib/errors/ValidatePathError.ts
  packages/core/src/lib/jdk/JdkHelper.ts
Labels: internal

#321 Enable a ChromeOS Only Build
  packages/core/src/lib/TwaManifest.ts
  packages/core/src/spec/lib/TwaManifestSpec.ts
  packages/core/template_project/app/src/main/AndroidManifest.xml
Labels: enhancement

#319 Include path instruction for spaces
  packages/cli/README.md
Labels: documentation

#318 Small addition of GUI tools to create APK
  README.md
Labels: documentation

#327 Cleans project before updating
  packages/cli/src/lib/cmds/update.ts
  packages/core/src/lib/TwaGenerator.ts
  packages/core/src/spec/lib/TwaGeneratorSpec.ts
Labels: bug

#315 Add JdkInstaller
  packages/cli/src/lib/config.ts
  packages/core/src/index.ts
  packages/core/src/lib/jdk/JdkInstaller.ts
Labels: enhancement

#323 Add a version code prompt
  packages/cli/src/lib/cmds/init.ts
  packages/cli/src/lib/inputHelpers.ts
  packages/cli/src/lib/strings.ts
Labels: enhancement

#345 Fixed targetClass for shortcuts
  packages/core/template_project/app/build.gradle
Labels: bug
