Repository GoogleChromeLabs/bubblewrap, pull requests merged in 2020-08, with the labels that each got.

#277 Fixed typo on help command
  packages/cli/src/lib/cmds/help.ts
Labels: bug

#283 Sanitize package.json files
  package-lock.json
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/validator/package.json
Labels: internal

#278 Supports enabling AppsFlyer Analytics
  packages/core/src/lib/TwaGenerator.ts
  packages/core/src/lib/TwaManifest.ts
  packages/core/src/lib/features/AppsFlyerFeature.ts
  packages/core/src/lib/features/Feature.ts
  packages/core/src/lib/features/FeatureManager.ts
  packages/core/src/spec/lib/features/AppsFlyerFeatureSpec.ts
  packages/core/src/spec/lib/features/FeatureManagerSpec.ts
  packages/core/template_project/app/build.gradle
  packages/core/template_project/app/src/main/AndroidManifest.xml
  packages/core/template_project/app/src/main/java/Application.java
  packages/core/template_project/app/src/main/java/LauncherActivity.java
Labels: enhancement

#290 Added `npm run clean`
  package-lock.json
  package.json
  packages/cli/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/validator/package-lock.json
  packages/validator/package.json
Labels: internal

#287 Add divider color functionality
  packages/core/src/lib/TwaManifest.ts
  packages/core/src/spec/lib/TwaManifestSpec.ts
  packages/core/template_project/app/build.gradle
  packages/core/template_project/app/src/main/AndroidManifest.xml
Labels: enhancement

#282 Make TWAs use Theme.Translucent.NoTitleBar
  packages/core/src/lib/TwaGenerator.ts
  packages/core/template_project/app/src/main/AndroidManifest.xml
  packages/core/template_project/app/src/main/res/values/styles.xml
Labels: enhancement
