Repository GoogleChromeLabs/bubblewrap, pull requests merged in 2020-10, with the labels that each got.

#352 chore: Update updateConfig usage message
  packages/cli/src/lib/strings.ts
Labels: bug

#369 Add diagram to README.
  packages/cli/README.md
  packages/cli/command_flow.dot
  packages/cli/command_flow.svg
Labels: documentation

#375 Create directory recursively installing JDK
  packages/cli/src/lib/config.ts
Labels: bug

#337 Auto download sdk
  packages/cli/src/lib/config.ts
  packages/cli/src/lib/strings.ts
  packages/cli/src/spec/configSpec.ts
  packages/core/src/index.ts
  packages/core/src/lib/androidSdk/AndroidSdkToolsInstaller.ts
  packages/core/src/lib/jdk/JdkInstaller.ts
Labels: enhancement
